using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace FakerLibrary.Test
{
    [TestClass]
    public class FakerTest
    {
        [TestMethod]
        public void CreateTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}