using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace ClassLibrary1lab_spp.Test
{
    [TestClass]
    public class SecondClassTest
    {
        [TestMethod]
        public void StartMethodTrace123Test()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void StopMethodTrace123Test()
        {
            Assert.Fail("autogenerated");
        }
    }
}