using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace ClassLibrary1lab_spp.Test
{
    [TestClass]
    public class TraceResultTest
    {
        [TestMethod]
        public void StartMethodTraceTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void StopMethodTraceTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}